# Generated by Django 3.2.6 on 2021-10-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='tmp_data')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Sales Records',
            },
        ),
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=20)),
                ('plan_type', models.CharField(choices=[('FORECAST', 'Forecast'), ('BUDGET', 'Budget')], default='FORECAST', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='sales_saleschannel_is_unique'),
        ),
        migrations.AddField(
            model_name='planitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
        ),
        migrations.AddField(
            model_name='planitem',
            name='sales_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesplan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='portfolio',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.saleschannel'),
        ),
        migrations.AddConstraint(
            model_name='salesplan',
            constraint=models.UniqueConstraint(fields=('period', 'customer', 'plan_type'), name='sales_salesplan_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.UniqueConstraint(fields=('sales_plan', 'product'), name='sales_planitem_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='sales_customer_is_unique'),
        ),
    ]
