# Generated by Django 3.2.6 on 2021-10-15 14:18

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0002_alter_customer_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FORECAST', 'Forecast'), ('BUDGET', 'Budget')], max_length=50, unique=True)),
                ('year', models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=sales.models.PlanType.current_year)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.plantype'),
        ),
    ]
